version: "3.9"
networks:
 roboshop:
  driver: bridge
services:
 web:
  image: srikanthhg/web:v1
  container_name: web
  ports:
  - "8080:80"
  depends_on:
  - catalogue
 mongodb:
  image: srikanthhg/mongo:v1
  container_name: mongodb
 catalogue:
  image: srikanthhg/catalogue:v1
  container_name: catalogue
  depends_on:
  - mongodb
 user:
  image: srikanthhg/user:v1
  container_name: user
  depends_on:
  - mongodb
  - redis
 redis:
  image: redis
 cart:
  image: srikanthhg/cart:v1
  container_name: cart
  depends_on:
  - redis
  - catalogue
